CREATE TABLE IF NOT EXISTS rsvps (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT,
  attendance TEXT NOT NULL,
  guests INTEGER NOT NULL DEFAULT 1,
  meal TEXT,
  message TEXT,
  created_at TEXT NOT NULL
);
